### ISSUE TITLE
add security page like on tendermint.com

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos.github.io#74]
include in nav or sub nav...

> jb: arguably this should be under "developers". non-devs don't need to learn about reporting vulnerabilities.

> adrian: I don't think that true. Even non-developers should know that we take security seriously, plus people shouldn't have to look for the place to report a vulnerability. It's the same story as with the validators page. Most users probably don't care either, but it is important.

@adrianbrink

**Comment by nylira** [comment]
Let's put it in the main nav. It's important enough to be there. I know the current contents of the security page is a little unreadable for non-developers. What we're going to have to do is improve the security index page so that it's more readable for the everyday user, and then create a dedicated bug report page.
